### ISSUE TITLE
Login/Register page

### ISSUE THREAD

**Issue by michaelschuff** [michaelschuff/FlashMath#5]
Users should navigate to the login page by default if not logged in. Login screen should resemble image below, featuring:

Login:
- email field
- password field
- Login Button
- switch to register page link

Register
- name field
- email field
- password field
- Register button
- switch to login page link

<img width="801" alt="login:registerpage" src="https://github.com/michaelschuff/FlashMath/assets/38889280/bf6003c8-bd1e-4458-95f2-5768c61e2243">

**Comment by JacobHeltonDev** [comment]
I wouldn't mind working on this for you, could you assign this issue to me?
